sudo: false
language: go
go:
  - "1.14.x"
script:
  - export HDNS_TOKEN=$(./scripts/get-token.sh)
  - cat resp.json
  - make test
  - travis_wait 30 make testacc
  - make
  - ./scripts/delete-token.sh $HCLOUD_TOKEN
env:
  - GOFLAGS=-mod=vendor GO111MODULE=on
